// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "kmeans.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic kmeans::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic kmeans::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<16> kmeans::ap_ST_fsm_state1 = "1";
const sc_lv<16> kmeans::ap_ST_fsm_state2 = "10";
const sc_lv<16> kmeans::ap_ST_fsm_state3 = "100";
const sc_lv<16> kmeans::ap_ST_fsm_state4 = "1000";
const sc_lv<16> kmeans::ap_ST_fsm_state5 = "10000";
const sc_lv<16> kmeans::ap_ST_fsm_state6 = "100000";
const sc_lv<16> kmeans::ap_ST_fsm_state7 = "1000000";
const sc_lv<16> kmeans::ap_ST_fsm_state8 = "10000000";
const sc_lv<16> kmeans::ap_ST_fsm_state9 = "100000000";
const sc_lv<16> kmeans::ap_ST_fsm_state10 = "1000000000";
const sc_lv<16> kmeans::ap_ST_fsm_state11 = "10000000000";
const sc_lv<16> kmeans::ap_ST_fsm_state12 = "100000000000";
const sc_lv<16> kmeans::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<16> kmeans::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<16> kmeans::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<16> kmeans::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<32> kmeans::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> kmeans::ap_const_lv1_1 = "1";
const sc_lv<32> kmeans::ap_const_lv32_1 = "1";
const sc_lv<1> kmeans::ap_const_lv1_0 = "0";
const sc_lv<32> kmeans::ap_const_lv32_2 = "10";
const sc_lv<32> kmeans::ap_const_lv32_3 = "11";
const sc_lv<32> kmeans::ap_const_lv32_4 = "100";
const sc_lv<32> kmeans::ap_const_lv32_5 = "101";
const sc_lv<32> kmeans::ap_const_lv32_6 = "110";
const sc_lv<32> kmeans::ap_const_lv32_7 = "111";
const sc_lv<32> kmeans::ap_const_lv32_8 = "1000";
const sc_lv<32> kmeans::ap_const_lv32_9 = "1001";
const sc_lv<32> kmeans::ap_const_lv32_A = "1010";
const sc_lv<32> kmeans::ap_const_lv32_B = "1011";
const sc_lv<32> kmeans::ap_const_lv32_C = "1100";
const sc_lv<9> kmeans::ap_const_lv9_0 = "000000000";
const sc_lv<3> kmeans::ap_const_lv3_0 = "000";
const sc_lv<3> kmeans::ap_const_lv3_1 = "1";
const sc_lv<32> kmeans::ap_const_lv32_F = "1111";
const sc_lv<16> kmeans::ap_const_lv16_0 = "0000000000000000";
const sc_lv<16> kmeans::ap_const_lv16_32 = "110010";
const sc_lv<32> kmeans::ap_const_lv32_E = "1110";
const sc_lv<16> kmeans::ap_const_lv16_46 = "1000110";
const sc_lv<16> kmeans::ap_const_lv16_28 = "101000";
const sc_lv<32> kmeans::ap_const_lv32_D = "1101";
const sc_lv<16> kmeans::ap_const_lv16_DC = "11011100";
const sc_lv<9> kmeans::ap_const_lv9_100 = "100000000";
const sc_lv<9> kmeans::ap_const_lv9_1 = "1";
const sc_lv<8> kmeans::ap_const_lv8_0 = "00000000";
const sc_lv<3> kmeans::ap_const_lv3_4 = "100";
const sc_lv<32> kmeans::ap_const_lv32_28 = "101000";
const sc_lv<32> kmeans::ap_const_lv32_50 = "1010000";
const sc_lv<32> kmeans::ap_const_lv32_B4 = "10110100";
const sc_lv<2> kmeans::ap_const_lv2_2 = "10";
const sc_lv<2> kmeans::ap_const_lv2_1 = "1";
const sc_lv<2> kmeans::ap_const_lv2_0 = "00";
const sc_lv<16> kmeans::ap_const_lv16_1 = "1";
const sc_lv<16> kmeans::ap_const_lv16_2 = "10";
const sc_lv<16> kmeans::ap_const_lv16_3 = "11";

kmeans::kmeans(sc_module_name name) : sc_module(name), mVcdFile(0) {
    empty_U = new kmeans_empty("empty_U");
    empty_U->clk(ap_clk);
    empty_U->reset(ap_rst);
    empty_U->address0(empty_address0);
    empty_U->ce0(empty_ce0);
    empty_U->we0(empty_we0);
    empty_U->d0(empty_d0);
    empty_U->q0(empty_q0);
    empty_3_U = new kmeans_empty("empty_3_U");
    empty_3_U->clk(ap_clk);
    empty_3_U->reset(ap_rst);
    empty_3_U->address0(empty_3_address0);
    empty_3_U->ce0(empty_3_ce0);
    empty_3_U->we0(empty_3_we0);
    empty_3_U->d0(empty_3_d0);
    empty_3_U->q0(empty_3_q0);
    empty_4_U = new kmeans_empty("empty_4_U");
    empty_4_U->clk(ap_clk);
    empty_4_U->reset(ap_rst);
    empty_4_U->address0(empty_4_address0);
    empty_4_U->ce0(empty_4_ce0);
    empty_4_U->we0(empty_4_we0);
    empty_4_U->d0(empty_4_d0);
    empty_4_U->q0(empty_4_q0);
    empty_5_U = new kmeans_empty("empty_5_U");
    empty_5_U->clk(ap_clk);
    empty_5_U->reset(ap_rst);
    empty_5_U->address0(empty_5_address0);
    empty_5_U->ce0(empty_5_ce0);
    empty_5_U->we0(empty_5_we0);
    empty_5_U->d0(empty_5_d0);
    empty_5_U->q0(empty_5_q0);
    kmeans_mux_42_32_1_U0 = new kmeans_mux_42_32_1<1,1,32,32,32,32,2,32>("kmeans_mux_42_32_1_U0");
    kmeans_mux_42_32_1_U0->din1(ap_var_for_const0);
    kmeans_mux_42_32_1_U0->din2(ap_var_for_const1);
    kmeans_mux_42_32_1_U0->din3(ap_var_for_const2);
    kmeans_mux_42_32_1_U0->din4(ap_var_for_const3);
    kmeans_mux_42_32_1_U0->din5(tmp_23_fu_492_p1);
    kmeans_mux_42_32_1_U0->dout(tmp_fu_496_p6);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ab_0_fu_531_p3);
    sensitive << ( tmp_24_fu_515_p1 );
    sensitive << ( abscond_fu_519_p2 );
    sensitive << ( tmp_11_fu_525_p2 );

    SC_METHOD(thread_ab_3_14_fu_621_p3);
    sensitive << ( ab_3_6_fu_92 );
    sensitive << ( ab_0_fu_531_p3 );
    sensitive << ( sel_tmp4_fu_567_p2 );

    SC_METHOD(thread_ab_3_15_fu_669_p3);
    sensitive << ( ab_3_10_fu_100 );
    sensitive << ( ab_3_11_fu_104 );
    sensitive << ( sel_tmp3_fu_663_p2 );

    SC_METHOD(thread_ab_3_17_fu_683_p3);
    sensitive << ( ab_3_9_fu_96 );
    sensitive << ( sel_tmp6_fu_677_p2 );
    sensitive << ( ab_3_15_fu_669_p3 );

    SC_METHOD(thread_ab_3_1_fu_559_p3);
    sensitive << ( ab_3_11_fu_104 );
    sensitive << ( sel_tmp2_fu_553_p2 );
    sensitive << ( ab_3_fu_545_p3 );

    SC_METHOD(thread_ab_3_2_fu_573_p3);
    sensitive << ( ab_3_11_fu_104 );
    sensitive << ( sel_tmp4_fu_567_p2 );
    sensitive << ( ab_3_1_fu_559_p3 );

    SC_METHOD(thread_ab_3_3_fu_581_p3);
    sensitive << ( ab_3_10_fu_100 );
    sensitive << ( sel_tmp_fu_539_p2 );
    sensitive << ( ab_0_fu_531_p3 );

    SC_METHOD(thread_ab_3_4_fu_589_p3);
    sensitive << ( ab_3_10_fu_100 );
    sensitive << ( sel_tmp2_fu_553_p2 );
    sensitive << ( ab_3_3_fu_581_p3 );

    SC_METHOD(thread_ab_3_5_fu_597_p3);
    sensitive << ( ab_3_10_fu_100 );
    sensitive << ( sel_tmp4_fu_567_p2 );
    sensitive << ( ab_3_4_fu_589_p3 );

    SC_METHOD(thread_ab_3_7_fu_605_p3);
    sensitive << ( ab_3_9_fu_96 );
    sensitive << ( ab_0_fu_531_p3 );
    sensitive << ( sel_tmp2_fu_553_p2 );

    SC_METHOD(thread_ab_3_8_fu_613_p3);
    sensitive << ( ab_3_9_fu_96 );
    sensitive << ( sel_tmp4_fu_567_p2 );
    sensitive << ( ab_3_7_fu_605_p3 );

    SC_METHOD(thread_ab_3_fu_545_p3);
    sensitive << ( ab_3_11_fu_104 );
    sensitive << ( sel_tmp_fu_539_p2 );
    sensitive << ( ab_0_fu_531_p3 );

    SC_METHOD(thread_abscond_fu_519_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond8_fu_480_p2 );
    sensitive << ( tmp_8_fu_510_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( exitcond6_fu_793_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( exitcond6_fu_793_p2 );

    SC_METHOD(thread_cluster_3_cast_fu_649_p1);
    sensitive << ( cluster_1_reg_304 );

    SC_METHOD(thread_cluster_4_cluster_2_fu_697_p3);
    sensitive << ( cluster_fu_88 );
    sensitive << ( tmp_15_fu_691_p2 );
    sensitive << ( cluster_3_cast_fu_649_p1 );

    SC_METHOD(thread_empty_3_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( p_sum_cast_reg_1091 );
    sensitive << ( p_addr_5_reg_1106 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( p_sum1_cast_fu_399_p1 );
    sensitive << ( p_sum4_cast_fu_752_p1 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_empty_3_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_empty_3_d0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( r_reg_1009 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_empty_3_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond9_fu_653_p2 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( exitcond3_fu_382_p2 );
    sensitive << ( tmp_17_fu_742_p2 );
    sensitive << ( tmp_12_fu_875_p2 );

    SC_METHOD(thread_empty_4_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( p_sum_cast_reg_1091 );
    sensitive << ( p_addr_6_reg_1114 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( p_sum1_cast_fu_399_p1 );
    sensitive << ( p_sum5_cast_fu_770_p1 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_empty_4_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_empty_4_d0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( r_reg_1009 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_empty_4_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond9_fu_653_p2 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( exitcond3_fu_382_p2 );
    sensitive << ( tmp_19_fu_760_p2 );
    sensitive << ( tmp_13_fu_881_p2 );

    SC_METHOD(thread_empty_5_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( p_sum_cast_reg_1091 );
    sensitive << ( p_addr_8_reg_1122 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( p_sum1_cast_fu_399_p1 );
    sensitive << ( p_sum6_cast_fu_788_p1 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_empty_5_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_empty_5_d0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( r_reg_1009 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_empty_5_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond9_fu_653_p2 );
    sensitive << ( exitcond3_fu_382_p2 );
    sensitive << ( tmp_20_fu_778_p2 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( tmp_16_fu_887_p2 );

    SC_METHOD(thread_empty_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( p_sum_cast_fu_864_p1 );
    sensitive << ( p_addr_4_reg_1098 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( p_sum1_cast_fu_399_p1 );
    sensitive << ( p_sum3_cast_fu_734_p1 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_empty_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_empty_d0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( r_reg_1009 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_empty_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond9_fu_653_p2 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( exitcond3_fu_382_p2 );
    sensitive << ( tmp_14_fu_724_p2 );
    sensitive << ( tmp_7_fu_869_p2 );

    SC_METHOD(thread_exitcond1_fu_349_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( s_reg_239 );

    SC_METHOD(thread_exitcond2_fu_407_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( i_reg_261 );

    SC_METHOD(thread_exitcond3_fu_382_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( t_reg_250 );

    SC_METHOD(thread_exitcond5_fu_443_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( j_reg_272 );

    SC_METHOD(thread_exitcond6_fu_793_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( l_reg_315 );

    SC_METHOD(thread_exitcond8_fu_480_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( p_reg_284 );

    SC_METHOD(thread_exitcond9_fu_653_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( cluster_1_reg_304 );

    SC_METHOD(thread_exitcond_fu_829_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( q_reg_326 );

    SC_METHOD(thread_final_address0);
    sensitive << ( final_addr_reg_1086 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_final_ce0);
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_final_d0);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( tmp2_fu_899_p2 );
    sensitive << ( tmp1_fu_893_p2 );

    SC_METHOD(thread_final_we0);
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_i_1_fu_413_p2);
    sensitive << ( i_reg_261 );

    SC_METHOD(thread_image_in_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_26_cast_fu_464_p1 );

    SC_METHOD(thread_image_in_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_j_1_fu_449_p2);
    sensitive << ( j_reg_272 );

    SC_METHOD(thread_l_1_fu_799_p2);
    sensitive << ( l_reg_315 );

    SC_METHOD(thread_min_2_phi_min1_fu_705_p3);
    sensitive << ( min1_reg_295 );
    sensitive << ( ab_3_17_fu_683_p3 );
    sensitive << ( tmp_15_fu_691_p2 );

    SC_METHOD(thread_p_1_fu_486_p2);
    sensitive << ( p_reg_284 );

    SC_METHOD(thread_p_2_fu_713_p2);
    sensitive << ( cluster_1_reg_304 );

    SC_METHOD(thread_p_sum1_cast_fu_399_p1);
    sensitive << ( p_sum1_fu_394_p2 );

    SC_METHOD(thread_p_sum1_fu_394_p2);
    sensitive << ( tmp_1_reg_920 );
    sensitive << ( t_cast_fu_378_p1 );

    SC_METHOD(thread_p_sum3_cast_fu_734_p1);
    sensitive << ( p_sum3_fu_730_p2 );

    SC_METHOD(thread_p_sum3_fu_730_p2);
    sensitive << ( tmp_3_reg_980 );
    sensitive << ( tmp_cast_reg_1001 );

    SC_METHOD(thread_p_sum4_cast_fu_752_p1);
    sensitive << ( p_sum4_fu_748_p2 );

    SC_METHOD(thread_p_sum4_fu_748_p2);
    sensitive << ( tmp_3_reg_980 );
    sensitive << ( tmp_cast_reg_1001 );

    SC_METHOD(thread_p_sum5_cast_fu_770_p1);
    sensitive << ( p_sum5_fu_766_p2 );

    SC_METHOD(thread_p_sum5_fu_766_p2);
    sensitive << ( tmp_3_reg_980 );
    sensitive << ( tmp_cast_reg_1001 );

    SC_METHOD(thread_p_sum6_cast_fu_788_p1);
    sensitive << ( p_sum6_fu_784_p2 );

    SC_METHOD(thread_p_sum6_fu_784_p2);
    sensitive << ( tmp_3_reg_980 );
    sensitive << ( tmp_cast_reg_1001 );

    SC_METHOD(thread_p_sum_cast_fu_864_p1);
    sensitive << ( p_sum_fu_859_p2 );

    SC_METHOD(thread_p_sum_fu_859_p2);
    sensitive << ( tmp_9_reg_1073 );
    sensitive << ( tmp_11_cast_fu_855_p1 );

    SC_METHOD(thread_q_1_fu_835_p2);
    sensitive << ( q_reg_326 );

    SC_METHOD(thread_s_1_fu_355_p2);
    sensitive << ( s_reg_239 );

    SC_METHOD(thread_sel_tmp2_fu_553_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond8_fu_480_p2 );
    sensitive << ( tmp_23_fu_492_p1 );

    SC_METHOD(thread_sel_tmp3_fu_663_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond9_fu_653_p2 );
    sensitive << ( tmp_25_fu_659_p1 );

    SC_METHOD(thread_sel_tmp4_fu_567_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond8_fu_480_p2 );
    sensitive << ( tmp_23_fu_492_p1 );

    SC_METHOD(thread_sel_tmp6_fu_677_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond9_fu_653_p2 );
    sensitive << ( tmp_25_fu_659_p1 );

    SC_METHOD(thread_sel_tmp_fu_539_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond8_fu_480_p2 );
    sensitive << ( tmp_23_fu_492_p1 );

    SC_METHOD(thread_t_1_fu_388_p2);
    sensitive << ( t_reg_250 );

    SC_METHOD(thread_t_cast_fu_378_p1);
    sensitive << ( t_reg_250 );

    SC_METHOD(thread_tmp1_fu_893_p2);
    sensitive << ( empty_q0 );
    sensitive << ( empty_3_q0 );

    SC_METHOD(thread_tmp2_fu_899_p2);
    sensitive << ( empty_4_q0 );
    sensitive << ( empty_5_q0 );

    SC_METHOD(thread_tmp_10_fu_817_p1);
    sensitive << ( l_reg_315 );

    SC_METHOD(thread_tmp_11_cast_fu_855_p1);
    sensitive << ( q_reg_326 );

    SC_METHOD(thread_tmp_11_fu_525_p2);
    sensitive << ( tmp_24_fu_515_p1 );

    SC_METHOD(thread_tmp_12_fu_875_p2);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( empty_3_q0 );

    SC_METHOD(thread_tmp_13_fu_881_p2);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( empty_4_q0 );

    SC_METHOD(thread_tmp_14_fu_724_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond9_fu_653_p2 );
    sensitive << ( cluster_fu_88 );

    SC_METHOD(thread_tmp_15_fu_691_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond9_fu_653_p2 );
    sensitive << ( min1_reg_295 );
    sensitive << ( ab_3_17_fu_683_p3 );

    SC_METHOD(thread_tmp_16_fu_887_p2);
    sensitive << ( empty_5_q0 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_tmp_17_fu_742_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond9_fu_653_p2 );
    sensitive << ( cluster_fu_88 );

    SC_METHOD(thread_tmp_19_fu_760_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond9_fu_653_p2 );
    sensitive << ( cluster_fu_88 );

    SC_METHOD(thread_tmp_1_fu_365_p3);
    sensitive << ( tmp_2_fu_361_p1 );

    SC_METHOD(thread_tmp_20_fu_778_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond9_fu_653_p2 );
    sensitive << ( cluster_fu_88 );

    SC_METHOD(thread_tmp_21_cast_fu_427_p1);
    sensitive << ( tmp_6_fu_419_p3 );

    SC_METHOD(thread_tmp_21_fu_459_p2);
    sensitive << ( tmp_21_cast_reg_975 );
    sensitive << ( tmp_cast1_fu_455_p1 );

    SC_METHOD(thread_tmp_22_fu_845_p2);
    sensitive << ( tmp_24_cast_reg_1068 );
    sensitive << ( tmp_5_cast_fu_841_p1 );

    SC_METHOD(thread_tmp_23_fu_492_p1);
    sensitive << ( p_reg_284 );

    SC_METHOD(thread_tmp_24_cast_fu_813_p1);
    sensitive << ( tmp_s_fu_805_p3 );

    SC_METHOD(thread_tmp_24_fu_515_p1);
    sensitive << ( tmp_8_fu_510_p2 );

    SC_METHOD(thread_tmp_25_fu_659_p1);
    sensitive << ( cluster_1_reg_304 );

    SC_METHOD(thread_tmp_26_cast_fu_464_p1);
    sensitive << ( tmp_21_fu_459_p2 );

    SC_METHOD(thread_tmp_27_cast_fu_850_p1);
    sensitive << ( tmp_22_fu_845_p2 );

    SC_METHOD(thread_tmp_2_fu_361_p1);
    sensitive << ( s_reg_239 );

    SC_METHOD(thread_tmp_3_fu_435_p3);
    sensitive << ( tmp_5_fu_431_p1 );

    SC_METHOD(thread_tmp_4_fu_473_p1);
    sensitive << ( image_in_q0 );

    SC_METHOD(thread_tmp_5_cast_fu_841_p1);
    sensitive << ( q_reg_326 );

    SC_METHOD(thread_tmp_5_fu_431_p1);
    sensitive << ( i_reg_261 );

    SC_METHOD(thread_tmp_6_fu_419_p3);
    sensitive << ( i_reg_261 );

    SC_METHOD(thread_tmp_7_fu_869_p2);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( empty_q0 );

    SC_METHOD(thread_tmp_8_fu_510_p2);
    sensitive << ( tmp_4_reg_1017 );
    sensitive << ( tmp_fu_496_p6 );

    SC_METHOD(thread_tmp_9_fu_821_p3);
    sensitive << ( tmp_10_fu_817_p1 );

    SC_METHOD(thread_tmp_cast1_fu_455_p1);
    sensitive << ( j_reg_272 );

    SC_METHOD(thread_tmp_cast_fu_469_p1);
    sensitive << ( j_reg_272 );

    SC_METHOD(thread_tmp_s_fu_805_p3);
    sensitive << ( l_reg_315 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond1_fu_349_p2 );
    sensitive << ( exitcond2_fu_407_p2 );
    sensitive << ( exitcond5_fu_443_p2 );
    sensitive << ( exitcond9_fu_653_p2 );
    sensitive << ( exitcond6_fu_793_p2 );
    sensitive << ( exitcond_fu_829_p2 );
    sensitive << ( exitcond3_fu_382_p2 );
    sensitive << ( exitcond8_fu_480_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const3);

    ap_CS_fsm = "0000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "kmeans_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, image_in_address0, "(port)image_in_address0");
    sc_trace(mVcdFile, image_in_ce0, "(port)image_in_ce0");
    sc_trace(mVcdFile, image_in_q0, "(port)image_in_q0");
    sc_trace(mVcdFile, final_address0, "(port)final_address0");
    sc_trace(mVcdFile, final_ce0, "(port)final_ce0");
    sc_trace(mVcdFile, final_we0, "(port)final_we0");
    sc_trace(mVcdFile, final_d0, "(port)final_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, s_1_fu_355_p2, "s_1_fu_355_p2");
    sc_trace(mVcdFile, s_1_reg_915, "s_1_reg_915");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_1_fu_365_p3, "tmp_1_fu_365_p3");
    sc_trace(mVcdFile, tmp_1_reg_920, "tmp_1_reg_920");
    sc_trace(mVcdFile, exitcond1_fu_349_p2, "exitcond1_fu_349_p2");
    sc_trace(mVcdFile, t_1_fu_388_p2, "t_1_fu_388_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_1_fu_413_p2, "i_1_fu_413_p2");
    sc_trace(mVcdFile, i_1_reg_970, "i_1_reg_970");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_21_cast_fu_427_p1, "tmp_21_cast_fu_427_p1");
    sc_trace(mVcdFile, tmp_21_cast_reg_975, "tmp_21_cast_reg_975");
    sc_trace(mVcdFile, exitcond2_fu_407_p2, "exitcond2_fu_407_p2");
    sc_trace(mVcdFile, tmp_3_fu_435_p3, "tmp_3_fu_435_p3");
    sc_trace(mVcdFile, tmp_3_reg_980, "tmp_3_reg_980");
    sc_trace(mVcdFile, j_1_fu_449_p2, "j_1_fu_449_p2");
    sc_trace(mVcdFile, j_1_reg_991, "j_1_reg_991");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, exitcond5_fu_443_p2, "exitcond5_fu_443_p2");
    sc_trace(mVcdFile, tmp_cast_fu_469_p1, "tmp_cast_fu_469_p1");
    sc_trace(mVcdFile, tmp_cast_reg_1001, "tmp_cast_reg_1001");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, r_reg_1009, "r_reg_1009");
    sc_trace(mVcdFile, tmp_4_fu_473_p1, "tmp_4_fu_473_p1");
    sc_trace(mVcdFile, tmp_4_reg_1017, "tmp_4_reg_1017");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, p_1_fu_486_p2, "p_1_fu_486_p2");
    sc_trace(mVcdFile, min_2_phi_min1_fu_705_p3, "min_2_phi_min1_fu_705_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, exitcond9_fu_653_p2, "exitcond9_fu_653_p2");
    sc_trace(mVcdFile, p_2_fu_713_p2, "p_2_fu_713_p2");
    sc_trace(mVcdFile, l_1_fu_799_p2, "l_1_fu_799_p2");
    sc_trace(mVcdFile, l_1_reg_1063, "l_1_reg_1063");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, tmp_24_cast_fu_813_p1, "tmp_24_cast_fu_813_p1");
    sc_trace(mVcdFile, tmp_24_cast_reg_1068, "tmp_24_cast_reg_1068");
    sc_trace(mVcdFile, exitcond6_fu_793_p2, "exitcond6_fu_793_p2");
    sc_trace(mVcdFile, tmp_9_fu_821_p3, "tmp_9_fu_821_p3");
    sc_trace(mVcdFile, tmp_9_reg_1073, "tmp_9_reg_1073");
    sc_trace(mVcdFile, q_1_fu_835_p2, "q_1_fu_835_p2");
    sc_trace(mVcdFile, q_1_reg_1081, "q_1_reg_1081");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, final_addr_reg_1086, "final_addr_reg_1086");
    sc_trace(mVcdFile, exitcond_fu_829_p2, "exitcond_fu_829_p2");
    sc_trace(mVcdFile, p_sum_cast_fu_864_p1, "p_sum_cast_fu_864_p1");
    sc_trace(mVcdFile, p_sum_cast_reg_1091, "p_sum_cast_reg_1091");
    sc_trace(mVcdFile, p_addr_4_reg_1098, "p_addr_4_reg_1098");
    sc_trace(mVcdFile, p_addr_5_reg_1106, "p_addr_5_reg_1106");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, p_addr_6_reg_1114, "p_addr_6_reg_1114");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, p_addr_8_reg_1122, "p_addr_8_reg_1122");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, empty_address0, "empty_address0");
    sc_trace(mVcdFile, empty_ce0, "empty_ce0");
    sc_trace(mVcdFile, empty_we0, "empty_we0");
    sc_trace(mVcdFile, empty_d0, "empty_d0");
    sc_trace(mVcdFile, empty_q0, "empty_q0");
    sc_trace(mVcdFile, empty_3_address0, "empty_3_address0");
    sc_trace(mVcdFile, empty_3_ce0, "empty_3_ce0");
    sc_trace(mVcdFile, empty_3_we0, "empty_3_we0");
    sc_trace(mVcdFile, empty_3_d0, "empty_3_d0");
    sc_trace(mVcdFile, empty_3_q0, "empty_3_q0");
    sc_trace(mVcdFile, empty_4_address0, "empty_4_address0");
    sc_trace(mVcdFile, empty_4_ce0, "empty_4_ce0");
    sc_trace(mVcdFile, empty_4_we0, "empty_4_we0");
    sc_trace(mVcdFile, empty_4_d0, "empty_4_d0");
    sc_trace(mVcdFile, empty_4_q0, "empty_4_q0");
    sc_trace(mVcdFile, empty_5_address0, "empty_5_address0");
    sc_trace(mVcdFile, empty_5_ce0, "empty_5_ce0");
    sc_trace(mVcdFile, empty_5_we0, "empty_5_we0");
    sc_trace(mVcdFile, empty_5_d0, "empty_5_d0");
    sc_trace(mVcdFile, empty_5_q0, "empty_5_q0");
    sc_trace(mVcdFile, s_reg_239, "s_reg_239");
    sc_trace(mVcdFile, exitcond3_fu_382_p2, "exitcond3_fu_382_p2");
    sc_trace(mVcdFile, t_reg_250, "t_reg_250");
    sc_trace(mVcdFile, i_reg_261, "i_reg_261");
    sc_trace(mVcdFile, j_reg_272, "j_reg_272");
    sc_trace(mVcdFile, p_reg_284, "p_reg_284");
    sc_trace(mVcdFile, exitcond8_fu_480_p2, "exitcond8_fu_480_p2");
    sc_trace(mVcdFile, min1_reg_295, "min1_reg_295");
    sc_trace(mVcdFile, cluster_1_reg_304, "cluster_1_reg_304");
    sc_trace(mVcdFile, l_reg_315, "l_reg_315");
    sc_trace(mVcdFile, q_reg_326, "q_reg_326");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, p_sum1_cast_fu_399_p1, "p_sum1_cast_fu_399_p1");
    sc_trace(mVcdFile, tmp_26_cast_fu_464_p1, "tmp_26_cast_fu_464_p1");
    sc_trace(mVcdFile, p_sum3_cast_fu_734_p1, "p_sum3_cast_fu_734_p1");
    sc_trace(mVcdFile, tmp_14_fu_724_p2, "tmp_14_fu_724_p2");
    sc_trace(mVcdFile, p_sum4_cast_fu_752_p1, "p_sum4_cast_fu_752_p1");
    sc_trace(mVcdFile, tmp_17_fu_742_p2, "tmp_17_fu_742_p2");
    sc_trace(mVcdFile, p_sum5_cast_fu_770_p1, "p_sum5_cast_fu_770_p1");
    sc_trace(mVcdFile, tmp_19_fu_760_p2, "tmp_19_fu_760_p2");
    sc_trace(mVcdFile, p_sum6_cast_fu_788_p1, "p_sum6_cast_fu_788_p1");
    sc_trace(mVcdFile, tmp_20_fu_778_p2, "tmp_20_fu_778_p2");
    sc_trace(mVcdFile, tmp_27_cast_fu_850_p1, "tmp_27_cast_fu_850_p1");
    sc_trace(mVcdFile, cluster_fu_88, "cluster_fu_88");
    sc_trace(mVcdFile, cluster_4_cluster_2_fu_697_p3, "cluster_4_cluster_2_fu_697_p3");
    sc_trace(mVcdFile, ab_3_6_fu_92, "ab_3_6_fu_92");
    sc_trace(mVcdFile, ab_3_14_fu_621_p3, "ab_3_14_fu_621_p3");
    sc_trace(mVcdFile, ab_3_9_fu_96, "ab_3_9_fu_96");
    sc_trace(mVcdFile, ab_3_8_fu_613_p3, "ab_3_8_fu_613_p3");
    sc_trace(mVcdFile, ab_3_10_fu_100, "ab_3_10_fu_100");
    sc_trace(mVcdFile, ab_3_5_fu_597_p3, "ab_3_5_fu_597_p3");
    sc_trace(mVcdFile, ab_3_11_fu_104, "ab_3_11_fu_104");
    sc_trace(mVcdFile, ab_3_2_fu_573_p3, "ab_3_2_fu_573_p3");
    sc_trace(mVcdFile, tmp_7_fu_869_p2, "tmp_7_fu_869_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, tmp_12_fu_875_p2, "tmp_12_fu_875_p2");
    sc_trace(mVcdFile, tmp_13_fu_881_p2, "tmp_13_fu_881_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, tmp_16_fu_887_p2, "tmp_16_fu_887_p2");
    sc_trace(mVcdFile, tmp_2_fu_361_p1, "tmp_2_fu_361_p1");
    sc_trace(mVcdFile, t_cast_fu_378_p1, "t_cast_fu_378_p1");
    sc_trace(mVcdFile, p_sum1_fu_394_p2, "p_sum1_fu_394_p2");
    sc_trace(mVcdFile, tmp_6_fu_419_p3, "tmp_6_fu_419_p3");
    sc_trace(mVcdFile, tmp_5_fu_431_p1, "tmp_5_fu_431_p1");
    sc_trace(mVcdFile, tmp_cast1_fu_455_p1, "tmp_cast1_fu_455_p1");
    sc_trace(mVcdFile, tmp_21_fu_459_p2, "tmp_21_fu_459_p2");
    sc_trace(mVcdFile, tmp_23_fu_492_p1, "tmp_23_fu_492_p1");
    sc_trace(mVcdFile, tmp_fu_496_p6, "tmp_fu_496_p6");
    sc_trace(mVcdFile, tmp_8_fu_510_p2, "tmp_8_fu_510_p2");
    sc_trace(mVcdFile, tmp_24_fu_515_p1, "tmp_24_fu_515_p1");
    sc_trace(mVcdFile, abscond_fu_519_p2, "abscond_fu_519_p2");
    sc_trace(mVcdFile, tmp_11_fu_525_p2, "tmp_11_fu_525_p2");
    sc_trace(mVcdFile, sel_tmp_fu_539_p2, "sel_tmp_fu_539_p2");
    sc_trace(mVcdFile, ab_0_fu_531_p3, "ab_0_fu_531_p3");
    sc_trace(mVcdFile, sel_tmp2_fu_553_p2, "sel_tmp2_fu_553_p2");
    sc_trace(mVcdFile, ab_3_fu_545_p3, "ab_3_fu_545_p3");
    sc_trace(mVcdFile, sel_tmp4_fu_567_p2, "sel_tmp4_fu_567_p2");
    sc_trace(mVcdFile, ab_3_1_fu_559_p3, "ab_3_1_fu_559_p3");
    sc_trace(mVcdFile, ab_3_3_fu_581_p3, "ab_3_3_fu_581_p3");
    sc_trace(mVcdFile, ab_3_4_fu_589_p3, "ab_3_4_fu_589_p3");
    sc_trace(mVcdFile, ab_3_7_fu_605_p3, "ab_3_7_fu_605_p3");
    sc_trace(mVcdFile, tmp_25_fu_659_p1, "tmp_25_fu_659_p1");
    sc_trace(mVcdFile, sel_tmp3_fu_663_p2, "sel_tmp3_fu_663_p2");
    sc_trace(mVcdFile, sel_tmp6_fu_677_p2, "sel_tmp6_fu_677_p2");
    sc_trace(mVcdFile, ab_3_15_fu_669_p3, "ab_3_15_fu_669_p3");
    sc_trace(mVcdFile, ab_3_17_fu_683_p3, "ab_3_17_fu_683_p3");
    sc_trace(mVcdFile, tmp_15_fu_691_p2, "tmp_15_fu_691_p2");
    sc_trace(mVcdFile, cluster_3_cast_fu_649_p1, "cluster_3_cast_fu_649_p1");
    sc_trace(mVcdFile, p_sum3_fu_730_p2, "p_sum3_fu_730_p2");
    sc_trace(mVcdFile, p_sum4_fu_748_p2, "p_sum4_fu_748_p2");
    sc_trace(mVcdFile, p_sum5_fu_766_p2, "p_sum5_fu_766_p2");
    sc_trace(mVcdFile, p_sum6_fu_784_p2, "p_sum6_fu_784_p2");
    sc_trace(mVcdFile, tmp_s_fu_805_p3, "tmp_s_fu_805_p3");
    sc_trace(mVcdFile, tmp_10_fu_817_p1, "tmp_10_fu_817_p1");
    sc_trace(mVcdFile, tmp_5_cast_fu_841_p1, "tmp_5_cast_fu_841_p1");
    sc_trace(mVcdFile, tmp_22_fu_845_p2, "tmp_22_fu_845_p2");
    sc_trace(mVcdFile, tmp_11_cast_fu_855_p1, "tmp_11_cast_fu_855_p1");
    sc_trace(mVcdFile, p_sum_fu_859_p2, "p_sum_fu_859_p2");
    sc_trace(mVcdFile, tmp2_fu_899_p2, "tmp2_fu_899_p2");
    sc_trace(mVcdFile, tmp1_fu_893_p2, "tmp1_fu_893_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("kmeans.hdltvin.dat");
    mHdltvoutHandle.open("kmeans.hdltvout.dat");
}

kmeans::~kmeans() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete empty_U;
    delete empty_3_U;
    delete empty_4_U;
    delete empty_5_U;
    delete kmeans_mux_42_32_1_U0;
}

void kmeans::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv32_5;
}

void kmeans::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv32_28;
}

void kmeans::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv32_50;
}

void kmeans::thread_ap_var_for_const3() {
    ap_var_for_const3 = ap_const_lv32_B4;
}

void kmeans::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_480_p2.read()))) {
        cluster_1_reg_304 = ap_const_lv3_1;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond9_fu_653_p2.read()))) {
        cluster_1_reg_304 = p_2_fu_713_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond9_fu_653_p2.read()))) {
        cluster_fu_88 = cluster_4_cluster_2_fu_697_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
                !esl_seteq<1,1,1>(exitcond1_fu_349_p2.read(), ap_const_lv1_0))) {
        cluster_fu_88 = ap_const_lv16_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_443_p2.read()))) {
        i_reg_261 = i_1_reg_970.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
                !esl_seteq<1,1,1>(exitcond1_fu_349_p2.read(), ap_const_lv1_0))) {
        i_reg_261 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond9_fu_653_p2.read()))) {
        j_reg_272 = j_1_reg_991.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_407_p2.read()))) {
        j_reg_272 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_407_p2.read()))) {
        l_reg_315 = ap_const_lv9_0;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state10.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_829_p2.read()))) {
        l_reg_315 = l_1_reg_1063.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_480_p2.read()))) {
        min1_reg_295 = ab_3_6_fu_92.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond9_fu_653_p2.read()))) {
        min1_reg_295 = min_2_phi_min1_fu_705_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_480_p2.read()))) {
        p_reg_284 = p_1_fu_486_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()))) {
        p_reg_284 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_793_p2.read()))) {
        q_reg_326 = ap_const_lv9_0;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state16.read()))) {
        q_reg_326 = q_1_reg_1081.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_382_p2.read()))) {
        s_reg_239 = s_1_reg_915.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        s_reg_239 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_349_p2.read(), ap_const_lv1_0))) {
        t_reg_250 = ap_const_lv9_0;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_382_p2.read()))) {
        t_reg_250 = t_1_fu_388_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_480_p2.read()))) {
        ab_3_10_fu_100 = ab_3_5_fu_597_p3.read();
        ab_3_11_fu_104 = ab_3_2_fu_573_p3.read();
        ab_3_6_fu_92 = ab_3_14_fu_621_p3.read();
        ab_3_9_fu_96 = ab_3_8_fu_613_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_829_p2.read()))) {
        final_addr_reg_1086 =  (sc_lv<16>) (tmp_27_cast_fu_850_p1.read());
        p_addr_4_reg_1098 =  (sc_lv<16>) (p_sum_cast_fu_864_p1.read());
        p_sum_cast_reg_1091 = p_sum_cast_fu_864_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()))) {
        i_1_reg_970 = i_1_fu_413_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()))) {
        j_1_reg_991 = j_1_fu_449_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read()))) {
        l_1_reg_1063 = l_1_fu_799_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state11.read()))) {
        p_addr_5_reg_1106 =  (sc_lv<16>) (p_sum_cast_reg_1091.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read()))) {
        p_addr_6_reg_1114 =  (sc_lv<16>) (p_sum_cast_reg_1091.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()))) {
        p_addr_8_reg_1122 =  (sc_lv<16>) (p_sum_cast_reg_1091.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state10.read()))) {
        q_1_reg_1081 = q_1_fu_835_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()))) {
        r_reg_1009 = image_in_q0.read();
        tmp_4_reg_1017 = tmp_4_fu_473_p1.read();
        tmp_cast_reg_1001 = tmp_cast_fu_469_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        s_1_reg_915 = s_1_fu_355_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond1_fu_349_p2.read(), ap_const_lv1_0))) {
        tmp_1_reg_920 = tmp_1_fu_365_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_407_p2.read()))) {
        tmp_21_cast_reg_975 = tmp_21_cast_fu_427_p1.read();
        tmp_3_reg_980 = tmp_3_fu_435_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_793_p2.read()))) {
        tmp_24_cast_reg_1068 = tmp_24_cast_fu_813_p1.read();
        tmp_9_reg_1073 = tmp_9_fu_821_p3.read();
    }
}

void kmeans::thread_ab_0_fu_531_p3() {
    ab_0_fu_531_p3 = (!abscond_fu_519_p2.read()[0].is_01())? sc_lv<16>(): ((abscond_fu_519_p2.read()[0].to_bool())? tmp_24_fu_515_p1.read(): tmp_11_fu_525_p2.read());
}

void kmeans::thread_ab_3_14_fu_621_p3() {
    ab_3_14_fu_621_p3 = (!sel_tmp4_fu_567_p2.read()[0].is_01())? sc_lv<16>(): ((sel_tmp4_fu_567_p2.read()[0].to_bool())? ab_0_fu_531_p3.read(): ab_3_6_fu_92.read());
}

void kmeans::thread_ab_3_15_fu_669_p3() {
    ab_3_15_fu_669_p3 = (!sel_tmp3_fu_663_p2.read()[0].is_01())? sc_lv<16>(): ((sel_tmp3_fu_663_p2.read()[0].to_bool())? ab_3_10_fu_100.read(): ab_3_11_fu_104.read());
}

void kmeans::thread_ab_3_17_fu_683_p3() {
    ab_3_17_fu_683_p3 = (!sel_tmp6_fu_677_p2.read()[0].is_01())? sc_lv<16>(): ((sel_tmp6_fu_677_p2.read()[0].to_bool())? ab_3_9_fu_96.read(): ab_3_15_fu_669_p3.read());
}

void kmeans::thread_ab_3_1_fu_559_p3() {
    ab_3_1_fu_559_p3 = (!sel_tmp2_fu_553_p2.read()[0].is_01())? sc_lv<16>(): ((sel_tmp2_fu_553_p2.read()[0].to_bool())? ab_3_11_fu_104.read(): ab_3_fu_545_p3.read());
}

void kmeans::thread_ab_3_2_fu_573_p3() {
    ab_3_2_fu_573_p3 = (!sel_tmp4_fu_567_p2.read()[0].is_01())? sc_lv<16>(): ((sel_tmp4_fu_567_p2.read()[0].to_bool())? ab_3_11_fu_104.read(): ab_3_1_fu_559_p3.read());
}

void kmeans::thread_ab_3_3_fu_581_p3() {
    ab_3_3_fu_581_p3 = (!sel_tmp_fu_539_p2.read()[0].is_01())? sc_lv<16>(): ((sel_tmp_fu_539_p2.read()[0].to_bool())? ab_0_fu_531_p3.read(): ab_3_10_fu_100.read());
}

void kmeans::thread_ab_3_4_fu_589_p3() {
    ab_3_4_fu_589_p3 = (!sel_tmp2_fu_553_p2.read()[0].is_01())? sc_lv<16>(): ((sel_tmp2_fu_553_p2.read()[0].to_bool())? ab_3_10_fu_100.read(): ab_3_3_fu_581_p3.read());
}

void kmeans::thread_ab_3_5_fu_597_p3() {
    ab_3_5_fu_597_p3 = (!sel_tmp4_fu_567_p2.read()[0].is_01())? sc_lv<16>(): ((sel_tmp4_fu_567_p2.read()[0].to_bool())? ab_3_10_fu_100.read(): ab_3_4_fu_589_p3.read());
}

void kmeans::thread_ab_3_7_fu_605_p3() {
    ab_3_7_fu_605_p3 = (!sel_tmp2_fu_553_p2.read()[0].is_01())? sc_lv<16>(): ((sel_tmp2_fu_553_p2.read()[0].to_bool())? ab_0_fu_531_p3.read(): ab_3_9_fu_96.read());
}

void kmeans::thread_ab_3_8_fu_613_p3() {
    ab_3_8_fu_613_p3 = (!sel_tmp4_fu_567_p2.read()[0].is_01())? sc_lv<16>(): ((sel_tmp4_fu_567_p2.read()[0].to_bool())? ab_3_9_fu_96.read(): ab_3_7_fu_605_p3.read());
}

void kmeans::thread_ab_3_fu_545_p3() {
    ab_3_fu_545_p3 = (!sel_tmp_fu_539_p2.read()[0].is_01())? sc_lv<16>(): ((sel_tmp_fu_539_p2.read()[0].to_bool())? ab_3_11_fu_104.read(): ab_0_fu_531_p3.read());
}

void kmeans::thread_abscond_fu_519_p2() {
    abscond_fu_519_p2 = (!tmp_8_fu_510_p2.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(tmp_8_fu_510_p2.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void kmeans::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read().range(0, 0);
}

void kmeans::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read().range(9, 9);
}

void kmeans::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read().range(10, 10);
}

void kmeans::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read().range(11, 11);
}

void kmeans::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read().range(12, 12);
}

void kmeans::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read().range(13, 13);
}

void kmeans::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read().range(14, 14);
}

void kmeans::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read().range(15, 15);
}

void kmeans::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read().range(1, 1);
}

void kmeans::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read().range(2, 2);
}

void kmeans::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read().range(3, 3);
}

void kmeans::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read().range(4, 4);
}

void kmeans::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read().range(5, 5);
}

void kmeans::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read().range(6, 6);
}

void kmeans::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read().range(7, 7);
}

void kmeans::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read().range(8, 8);
}

void kmeans::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_793_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void kmeans::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void kmeans::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_793_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void kmeans::thread_cluster_3_cast_fu_649_p1() {
    cluster_3_cast_fu_649_p1 = esl_zext<16,3>(cluster_1_reg_304.read());
}

void kmeans::thread_cluster_4_cluster_2_fu_697_p3() {
    cluster_4_cluster_2_fu_697_p3 = (!tmp_15_fu_691_p2.read()[0].is_01())? sc_lv<16>(): ((tmp_15_fu_691_p2.read()[0].to_bool())? cluster_3_cast_fu_649_p1.read(): cluster_fu_88.read());
}

void kmeans::thread_empty_3_address0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read())))) {
        empty_3_address0 = p_addr_5_reg_1106.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state11.read()))) {
        empty_3_address0 =  (sc_lv<16>) (p_sum_cast_reg_1091.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        empty_3_address0 =  (sc_lv<16>) (p_sum4_cast_fu_752_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        empty_3_address0 =  (sc_lv<16>) (p_sum1_cast_fu_399_p1.read());
    } else {
        empty_3_address0 = "XXXXXXXXXXXXXXXX";
    }
}

void kmeans::thread_empty_3_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state11.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read())))) {
        empty_3_ce0 = ap_const_logic_1;
    } else {
        empty_3_ce0 = ap_const_logic_0;
    }
}

void kmeans::thread_empty_3_d0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read()))) {
        empty_3_d0 = ap_const_lv16_46;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        empty_3_d0 = r_reg_1009.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        empty_3_d0 = ap_const_lv16_0;
    } else {
        empty_3_d0 = "XXXXXXXXXXXXXXXX";
    }
}

void kmeans::thread_empty_3_we0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_382_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond9_fu_653_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_17_fu_742_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_12_fu_875_p2.read())))) {
        empty_3_we0 = ap_const_logic_1;
    } else {
        empty_3_we0 = ap_const_logic_0;
    }
}

void kmeans::thread_empty_4_address0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read())))) {
        empty_4_address0 = p_addr_6_reg_1114.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read()))) {
        empty_4_address0 =  (sc_lv<16>) (p_sum_cast_reg_1091.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        empty_4_address0 =  (sc_lv<16>) (p_sum5_cast_fu_770_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        empty_4_address0 =  (sc_lv<16>) (p_sum1_cast_fu_399_p1.read());
    } else {
        empty_4_address0 = "XXXXXXXXXXXXXXXX";
    }
}

void kmeans::thread_empty_4_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read())))) {
        empty_4_ce0 = ap_const_logic_1;
    } else {
        empty_4_ce0 = ap_const_logic_0;
    }
}

void kmeans::thread_empty_4_d0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()))) {
        empty_4_d0 = ap_const_lv16_28;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        empty_4_d0 = r_reg_1009.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        empty_4_d0 = ap_const_lv16_0;
    } else {
        empty_4_d0 = "XXXXXXXXXXXXXXXX";
    }
}

void kmeans::thread_empty_4_we0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_382_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond9_fu_653_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_760_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_13_fu_881_p2.read())))) {
        empty_4_we0 = ap_const_logic_1;
    } else {
        empty_4_we0 = ap_const_logic_0;
    }
}

void kmeans::thread_empty_5_address0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read())))) {
        empty_5_address0 = p_addr_8_reg_1122.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()))) {
        empty_5_address0 =  (sc_lv<16>) (p_sum_cast_reg_1091.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        empty_5_address0 =  (sc_lv<16>) (p_sum6_cast_fu_788_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        empty_5_address0 =  (sc_lv<16>) (p_sum1_cast_fu_399_p1.read());
    } else {
        empty_5_address0 = "XXXXXXXXXXXXXXXX";
    }
}

void kmeans::thread_empty_5_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read())))) {
        empty_5_ce0 = ap_const_logic_1;
    } else {
        empty_5_ce0 = ap_const_logic_0;
    }
}

void kmeans::thread_empty_5_d0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read()))) {
        empty_5_d0 = ap_const_lv16_DC;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        empty_5_d0 = r_reg_1009.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        empty_5_d0 = ap_const_lv16_0;
    } else {
        empty_5_d0 = "XXXXXXXXXXXXXXXX";
    }
}

void kmeans::thread_empty_5_we0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_382_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond9_fu_653_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_20_fu_778_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_16_fu_887_p2.read())))) {
        empty_5_we0 = ap_const_logic_1;
    } else {
        empty_5_we0 = ap_const_logic_0;
    }
}

void kmeans::thread_empty_address0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state11.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read())))) {
        empty_address0 = p_addr_4_reg_1098.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state10.read()))) {
        empty_address0 =  (sc_lv<16>) (p_sum_cast_fu_864_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        empty_address0 =  (sc_lv<16>) (p_sum3_cast_fu_734_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        empty_address0 =  (sc_lv<16>) (p_sum1_cast_fu_399_p1.read());
    } else {
        empty_address0 = "XXXXXXXXXXXXXXXX";
    }
}

void kmeans::thread_empty_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state10.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state11.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read())))) {
        empty_ce0 = ap_const_logic_1;
    } else {
        empty_ce0 = ap_const_logic_0;
    }
}

void kmeans::thread_empty_d0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state11.read()))) {
        empty_d0 = ap_const_lv16_32;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        empty_d0 = r_reg_1009.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        empty_d0 = ap_const_lv16_0;
    } else {
        empty_d0 = "XXXXXXXXXXXXXXXX";
    }
}

void kmeans::thread_empty_we0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_382_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond9_fu_653_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_14_fu_724_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state11.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_fu_869_p2.read())))) {
        empty_we0 = ap_const_logic_1;
    } else {
        empty_we0 = ap_const_logic_0;
    }
}

void kmeans::thread_exitcond1_fu_349_p2() {
    exitcond1_fu_349_p2 = (!s_reg_239.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(s_reg_239.read() == ap_const_lv9_100);
}

void kmeans::thread_exitcond2_fu_407_p2() {
    exitcond2_fu_407_p2 = (!i_reg_261.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_261.read() == ap_const_lv9_100);
}

void kmeans::thread_exitcond3_fu_382_p2() {
    exitcond3_fu_382_p2 = (!t_reg_250.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(t_reg_250.read() == ap_const_lv9_100);
}

void kmeans::thread_exitcond5_fu_443_p2() {
    exitcond5_fu_443_p2 = (!j_reg_272.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_272.read() == ap_const_lv9_100);
}

void kmeans::thread_exitcond6_fu_793_p2() {
    exitcond6_fu_793_p2 = (!l_reg_315.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(l_reg_315.read() == ap_const_lv9_100);
}

void kmeans::thread_exitcond8_fu_480_p2() {
    exitcond8_fu_480_p2 = (!p_reg_284.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(p_reg_284.read() == ap_const_lv3_4);
}

void kmeans::thread_exitcond9_fu_653_p2() {
    exitcond9_fu_653_p2 = (!cluster_1_reg_304.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(cluster_1_reg_304.read() == ap_const_lv3_4);
}

void kmeans::thread_exitcond_fu_829_p2() {
    exitcond_fu_829_p2 = (!q_reg_326.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(q_reg_326.read() == ap_const_lv9_100);
}

void kmeans::thread_final_address0() {
    final_address0 = final_addr_reg_1086.read();
}

void kmeans::thread_final_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state16.read()))) {
        final_ce0 = ap_const_logic_1;
    } else {
        final_ce0 = ap_const_logic_0;
    }
}

void kmeans::thread_final_d0() {
    final_d0 = (!tmp2_fu_899_p2.read().is_01() || !tmp1_fu_893_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp2_fu_899_p2.read()) + sc_biguint<16>(tmp1_fu_893_p2.read()));
}

void kmeans::thread_final_we0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state16.read())))) {
        final_we0 = ap_const_logic_1;
    } else {
        final_we0 = ap_const_logic_0;
    }
}

void kmeans::thread_i_1_fu_413_p2() {
    i_1_fu_413_p2 = (!i_reg_261.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i_reg_261.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void kmeans::thread_image_in_address0() {
    image_in_address0 =  (sc_lv<16>) (tmp_26_cast_fu_464_p1.read());
}

void kmeans::thread_image_in_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()))) {
        image_in_ce0 = ap_const_logic_1;
    } else {
        image_in_ce0 = ap_const_logic_0;
    }
}

void kmeans::thread_j_1_fu_449_p2() {
    j_1_fu_449_p2 = (!j_reg_272.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(j_reg_272.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void kmeans::thread_l_1_fu_799_p2() {
    l_1_fu_799_p2 = (!l_reg_315.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(l_reg_315.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void kmeans::thread_min_2_phi_min1_fu_705_p3() {
    min_2_phi_min1_fu_705_p3 = (!tmp_15_fu_691_p2.read()[0].is_01())? sc_lv<16>(): ((tmp_15_fu_691_p2.read()[0].to_bool())? ab_3_17_fu_683_p3.read(): min1_reg_295.read());
}

void kmeans::thread_p_1_fu_486_p2() {
    p_1_fu_486_p2 = (!p_reg_284.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(p_reg_284.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void kmeans::thread_p_2_fu_713_p2() {
    p_2_fu_713_p2 = (!ap_const_lv3_1.is_01() || !cluster_1_reg_304.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_1) + sc_biguint<3>(cluster_1_reg_304.read()));
}

void kmeans::thread_p_sum1_cast_fu_399_p1() {
    p_sum1_cast_fu_399_p1 = esl_zext<32,16>(p_sum1_fu_394_p2.read());
}

void kmeans::thread_p_sum1_fu_394_p2() {
    p_sum1_fu_394_p2 = (!tmp_1_reg_920.read().is_01() || !t_cast_fu_378_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_1_reg_920.read()) + sc_biguint<16>(t_cast_fu_378_p1.read()));
}

void kmeans::thread_p_sum3_cast_fu_734_p1() {
    p_sum3_cast_fu_734_p1 = esl_zext<32,16>(p_sum3_fu_730_p2.read());
}

void kmeans::thread_p_sum3_fu_730_p2() {
    p_sum3_fu_730_p2 = (!tmp_3_reg_980.read().is_01() || !tmp_cast_reg_1001.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_3_reg_980.read()) + sc_biguint<16>(tmp_cast_reg_1001.read()));
}

void kmeans::thread_p_sum4_cast_fu_752_p1() {
    p_sum4_cast_fu_752_p1 = esl_zext<32,16>(p_sum4_fu_748_p2.read());
}

void kmeans::thread_p_sum4_fu_748_p2() {
    p_sum4_fu_748_p2 = (!tmp_3_reg_980.read().is_01() || !tmp_cast_reg_1001.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_3_reg_980.read()) + sc_biguint<16>(tmp_cast_reg_1001.read()));
}

void kmeans::thread_p_sum5_cast_fu_770_p1() {
    p_sum5_cast_fu_770_p1 = esl_zext<32,16>(p_sum5_fu_766_p2.read());
}

void kmeans::thread_p_sum5_fu_766_p2() {
    p_sum5_fu_766_p2 = (!tmp_3_reg_980.read().is_01() || !tmp_cast_reg_1001.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_3_reg_980.read()) + sc_biguint<16>(tmp_cast_reg_1001.read()));
}

void kmeans::thread_p_sum6_cast_fu_788_p1() {
    p_sum6_cast_fu_788_p1 = esl_zext<32,16>(p_sum6_fu_784_p2.read());
}

void kmeans::thread_p_sum6_fu_784_p2() {
    p_sum6_fu_784_p2 = (!tmp_3_reg_980.read().is_01() || !tmp_cast_reg_1001.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_3_reg_980.read()) + sc_biguint<16>(tmp_cast_reg_1001.read()));
}

void kmeans::thread_p_sum_cast_fu_864_p1() {
    p_sum_cast_fu_864_p1 = esl_zext<32,16>(p_sum_fu_859_p2.read());
}

void kmeans::thread_p_sum_fu_859_p2() {
    p_sum_fu_859_p2 = (!tmp_11_cast_fu_855_p1.read().is_01() || !tmp_9_reg_1073.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_11_cast_fu_855_p1.read()) + sc_biguint<16>(tmp_9_reg_1073.read()));
}

void kmeans::thread_q_1_fu_835_p2() {
    q_1_fu_835_p2 = (!q_reg_326.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(q_reg_326.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void kmeans::thread_s_1_fu_355_p2() {
    s_1_fu_355_p2 = (!s_reg_239.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(s_reg_239.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void kmeans::thread_sel_tmp2_fu_553_p2() {
    sel_tmp2_fu_553_p2 = (!tmp_23_fu_492_p1.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(tmp_23_fu_492_p1.read() == ap_const_lv2_1);
}

void kmeans::thread_sel_tmp3_fu_663_p2() {
    sel_tmp3_fu_663_p2 = (!tmp_25_fu_659_p1.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(tmp_25_fu_659_p1.read() == ap_const_lv2_2);
}

void kmeans::thread_sel_tmp4_fu_567_p2() {
    sel_tmp4_fu_567_p2 = (!tmp_23_fu_492_p1.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_23_fu_492_p1.read() == ap_const_lv2_0);
}

void kmeans::thread_sel_tmp6_fu_677_p2() {
    sel_tmp6_fu_677_p2 = (!tmp_25_fu_659_p1.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(tmp_25_fu_659_p1.read() == ap_const_lv2_1);
}

void kmeans::thread_sel_tmp_fu_539_p2() {
    sel_tmp_fu_539_p2 = (!tmp_23_fu_492_p1.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(tmp_23_fu_492_p1.read() == ap_const_lv2_2);
}

void kmeans::thread_t_1_fu_388_p2() {
    t_1_fu_388_p2 = (!t_reg_250.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(t_reg_250.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void kmeans::thread_t_cast_fu_378_p1() {
    t_cast_fu_378_p1 = esl_zext<16,9>(t_reg_250.read());
}

void kmeans::thread_tmp1_fu_893_p2() {
    tmp1_fu_893_p2 = (!empty_3_q0.read().is_01() || !empty_q0.read().is_01())? sc_lv<16>(): (sc_biguint<16>(empty_3_q0.read()) + sc_biguint<16>(empty_q0.read()));
}

void kmeans::thread_tmp2_fu_899_p2() {
    tmp2_fu_899_p2 = (!empty_4_q0.read().is_01() || !empty_5_q0.read().is_01())? sc_lv<16>(): (sc_biguint<16>(empty_4_q0.read()) + sc_biguint<16>(empty_5_q0.read()));
}

void kmeans::thread_tmp_10_fu_817_p1() {
    tmp_10_fu_817_p1 = l_reg_315.read().range(8-1, 0);
}

void kmeans::thread_tmp_11_cast_fu_855_p1() {
    tmp_11_cast_fu_855_p1 = esl_zext<16,9>(q_reg_326.read());
}

void kmeans::thread_tmp_11_fu_525_p2() {
    tmp_11_fu_525_p2 = (!ap_const_lv16_0.is_01() || !tmp_24_fu_515_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_0) - sc_biguint<16>(tmp_24_fu_515_p1.read()));
}

void kmeans::thread_tmp_12_fu_875_p2() {
    tmp_12_fu_875_p2 = (!empty_3_q0.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(empty_3_q0.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void kmeans::thread_tmp_13_fu_881_p2() {
    tmp_13_fu_881_p2 = (!empty_4_q0.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(empty_4_q0.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void kmeans::thread_tmp_14_fu_724_p2() {
    tmp_14_fu_724_p2 = (!cluster_fu_88.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): sc_lv<1>(cluster_fu_88.read() == ap_const_lv16_0);
}

void kmeans::thread_tmp_15_fu_691_p2() {
    tmp_15_fu_691_p2 = (!ab_3_17_fu_683_p3.read().is_01() || !min1_reg_295.read().is_01())? sc_lv<1>(): (sc_bigint<16>(ab_3_17_fu_683_p3.read()) < sc_bigint<16>(min1_reg_295.read()));
}

void kmeans::thread_tmp_16_fu_887_p2() {
    tmp_16_fu_887_p2 = (!empty_5_q0.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(empty_5_q0.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void kmeans::thread_tmp_17_fu_742_p2() {
    tmp_17_fu_742_p2 = (!cluster_fu_88.read().is_01() || !ap_const_lv16_1.is_01())? sc_lv<1>(): sc_lv<1>(cluster_fu_88.read() == ap_const_lv16_1);
}

void kmeans::thread_tmp_19_fu_760_p2() {
    tmp_19_fu_760_p2 = (!cluster_fu_88.read().is_01() || !ap_const_lv16_2.is_01())? sc_lv<1>(): sc_lv<1>(cluster_fu_88.read() == ap_const_lv16_2);
}

void kmeans::thread_tmp_1_fu_365_p3() {
    tmp_1_fu_365_p3 = esl_concat<8,8>(tmp_2_fu_361_p1.read(), ap_const_lv8_0);
}

void kmeans::thread_tmp_20_fu_778_p2() {
    tmp_20_fu_778_p2 = (!cluster_fu_88.read().is_01() || !ap_const_lv16_3.is_01())? sc_lv<1>(): sc_lv<1>(cluster_fu_88.read() == ap_const_lv16_3);
}

void kmeans::thread_tmp_21_cast_fu_427_p1() {
    tmp_21_cast_fu_427_p1 = esl_zext<18,17>(tmp_6_fu_419_p3.read());
}

void kmeans::thread_tmp_21_fu_459_p2() {
    tmp_21_fu_459_p2 = (!tmp_21_cast_reg_975.read().is_01() || !tmp_cast1_fu_455_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp_21_cast_reg_975.read()) + sc_biguint<18>(tmp_cast1_fu_455_p1.read()));
}

void kmeans::thread_tmp_22_fu_845_p2() {
    tmp_22_fu_845_p2 = (!tmp_24_cast_reg_1068.read().is_01() || !tmp_5_cast_fu_841_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp_24_cast_reg_1068.read()) + sc_biguint<18>(tmp_5_cast_fu_841_p1.read()));
}

void kmeans::thread_tmp_23_fu_492_p1() {
    tmp_23_fu_492_p1 = p_reg_284.read().range(2-1, 0);
}

void kmeans::thread_tmp_24_cast_fu_813_p1() {
    tmp_24_cast_fu_813_p1 = esl_zext<18,17>(tmp_s_fu_805_p3.read());
}

void kmeans::thread_tmp_24_fu_515_p1() {
    tmp_24_fu_515_p1 = tmp_8_fu_510_p2.read().range(16-1, 0);
}

void kmeans::thread_tmp_25_fu_659_p1() {
    tmp_25_fu_659_p1 = cluster_1_reg_304.read().range(2-1, 0);
}

void kmeans::thread_tmp_26_cast_fu_464_p1() {
    tmp_26_cast_fu_464_p1 = esl_zext<32,18>(tmp_21_fu_459_p2.read());
}

void kmeans::thread_tmp_27_cast_fu_850_p1() {
    tmp_27_cast_fu_850_p1 = esl_zext<32,18>(tmp_22_fu_845_p2.read());
}

void kmeans::thread_tmp_2_fu_361_p1() {
    tmp_2_fu_361_p1 = s_reg_239.read().range(8-1, 0);
}

void kmeans::thread_tmp_3_fu_435_p3() {
    tmp_3_fu_435_p3 = esl_concat<8,8>(tmp_5_fu_431_p1.read(), ap_const_lv8_0);
}

void kmeans::thread_tmp_4_fu_473_p1() {
    tmp_4_fu_473_p1 = esl_sext<32,16>(image_in_q0.read());
}

void kmeans::thread_tmp_5_cast_fu_841_p1() {
    tmp_5_cast_fu_841_p1 = esl_zext<18,9>(q_reg_326.read());
}

void kmeans::thread_tmp_5_fu_431_p1() {
    tmp_5_fu_431_p1 = i_reg_261.read().range(8-1, 0);
}

void kmeans::thread_tmp_6_fu_419_p3() {
    tmp_6_fu_419_p3 = esl_concat<9,8>(i_reg_261.read(), ap_const_lv8_0);
}

void kmeans::thread_tmp_7_fu_869_p2() {
    tmp_7_fu_869_p2 = (!empty_q0.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(empty_q0.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void kmeans::thread_tmp_8_fu_510_p2() {
    tmp_8_fu_510_p2 = (!tmp_4_reg_1017.read().is_01() || !tmp_fu_496_p6.read().is_01())? sc_lv<32>(): (sc_bigint<32>(tmp_4_reg_1017.read()) - sc_biguint<32>(tmp_fu_496_p6.read()));
}

void kmeans::thread_tmp_9_fu_821_p3() {
    tmp_9_fu_821_p3 = esl_concat<8,8>(tmp_10_fu_817_p1.read(), ap_const_lv8_0);
}

void kmeans::thread_tmp_cast1_fu_455_p1() {
    tmp_cast1_fu_455_p1 = esl_zext<18,9>(j_reg_272.read());
}

void kmeans::thread_tmp_cast_fu_469_p1() {
    tmp_cast_fu_469_p1 = esl_zext<16,9>(j_reg_272.read());
}

void kmeans::thread_tmp_s_fu_805_p3() {
    tmp_s_fu_805_p3 = esl_concat<9,8>(l_reg_315.read(), ap_const_lv8_0);
}

void kmeans::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(exitcond1_fu_349_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_382_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_407_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_443_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_480_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 128 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond9_fu_653_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 256 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_fu_793_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 512 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_829_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXXXXX";
            break;
    }
}

void kmeans::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"image_in_address0\" :  \"" << image_in_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"image_in_ce0\" :  \"" << image_in_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"image_in_q0\" :  \"" << image_in_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"final_address0\" :  \"" << final_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"final_ce0\" :  \"" << final_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"final_we0\" :  \"" << final_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"final_d0\" :  \"" << final_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

